### ISSUE TITLE
Can't install the game

### ISSUE THREAD

**Issue by plaseyaw** [DexterHuang/CyberCodeOnline#1062]
Can't install the game on my android, it's been quite some time since last time I have the game installed, and when I sent tho install the apk from aurora store, this error popped up : INSTALL_FAILED_INVALID_APK: missing codepath
and when i tried xapk installer, this one popped up:
com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor$BadContentProviderException: DISPLAY_NAME column is null
	at com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor.name(ContentUriFileDescriptor.java:30)
	at com.aefyr.sai.model.apksource.DefaultApkSource.getApkLocalPath(DefaultApkSource.java:47)
	at com.aefyr.sai.model.apksource.FilterApkSource.getApkLocalPath(FilterApkSource.java:60)
	at com.aefyr.sai.model.apksource.FilterApkSource.nextApk(FilterApkSource.java:28)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:93)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:70)
	at com.aefyr.sai.installer2.impl.rootless.-$$Lambda$RootlessSaiPackageInstaller$ivyAcunEgIkYlu_dB2vN6MOWZPU.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

Idk what am I supposed to do, send help it's 3 am 

Pictures:
![Screenshot_20211027-031109_XAPKS Installer](https://user-images.githubusercontent.com/75563600/138953667-62918a74-1804-4706-aecb-b60be8362302.jpg)
![Screenshot_20211027-031229_Aurora Store](https://user-images.githubusercontent.com/75563600/138953901-c18dc409-925c-499f-ad25-76bc9896ce94.jpg)

**Comment by hafizdkren** [comment]
I'll suggest to just install it from PS for moment. I think Dex can try to export onto APK and sending it to F-Droid, from there it would be just adding repo since Aurora is just tunneling some part but not all needed item.

Also, I'll try if this issue is just one device only or it is just problem with Aurora.

**Comment by hafizdkren** [comment]
After testing it with Aurora, it seem fine for me and my device.

Can you show us the screenshot of your installation setting. I've been using Session mode and it seem fine.
Thing that we need to consider is how the app store work with different installation. since for me it not support native but run well on Session mode I think the store/device is confuse on what it supposed to do with downloaded data.
