### ISSUE TITLE
Crash when trying to enter any level

### ISSUE THREAD

**Issue by twystd** [DexterHuang/CyberCodeOnline#133]
Hi,

After the last update, the app is crashing when trying to enter any area (and sometimes just when at the _HyperTrain_ station). It happens immediately when you click on an area (e.g. `goToFloriStation`) and fairly frequently after a delay when waiting at the _HyperTrain_ platform, and is happening across Chrome, Firefox and Safari.

The (decoded from base64) error message  is:

```
>urn r.createElement("div",{style:{whiteSpace:"pre-line",minWidth:512,padding:4}},r.createElement("p",null,e.to.getDescription().replace(/\s\s/gm," ").replace(/\n/gm,"")),s.length>0&&r.createElement("p",{style:{borderTop:"1px solid ".concat(i.a.PRIMARY_MEDI
                                                                                                                               ^


TypeError: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at tip (https://cybercodeonline.com/static/js/AppLayoutDesktop.acc79832.chunk.js:1:96765)
    at l.value (https://cybercodeonline.com/static/js/AppLayoutDesktop.acc79832.chunk.js:1:21879)
    at Ua (https://cybercodeonline.com/static/js/firestore.05b2e060.chunk.js:1:377892)
    at Fa (https://cybercodeonline.com/static/js/firestore.05b2e060.chunk.js:1:377685)
    at gu (https://cybercodeonline.com/static/js/firestore.05b2e060.chunk.js:1:413719)
    at gs (https://cybercodeonline.com/static/js/firestore.05b2e060.chunk.js:1:405042)
    at ms (https://cybercodeonline.com/static/js/firestore.05b2e060.chunk.js:1:404967)
    at cs (https://cybercodeonline.com/static/js/firestore.05b2e060.chunk.js:1:401969)
    at https://cybercodeonline.com/static/js/firestore.05b2e060.chunk.js:1:353159
    at t.unstable_runWithPriority (https://cybercodeonline.com/static/js/firestore.05b2e060.chunk.js:1:428829)
```

**Comment by DexterHuang** [comment]
hello! thank you for your bug report!  I have created a patch for this, please try again :)

**Comment by twystd** [comment]
Checked and it seems to be fixed. Thanks - that was fast!
