### ISSUE TITLE
Cannot submit 'forgot password' form

### ISSUE THREAD

**Issue by Siinamon** [DexterHuang/CyberCodeOnline#1394]
When I filled my email out on "forgot password" screen, upon pressing submit, I am sent to "Uh oh, my bad.. something went wrong" and am told to give ou this error code:

```
PnJpbmciIT09dHlwZW9mIGUpdGhyb3cgRXJyb3IoYSgyODQpKTtpZighbi5fb3duZXIpdGhyb3cgRXJyb3IoYSgyOTAsZSkpfXJldHVybiBlfWZ1bmN0aW9uIFNvKGUsdCl7aWYoInRleHRhcmVhIiE9PWUudHlwZSl0aHJvdyBFcnJvcihhKDMxLCJbb2JqZWN0IE9iamVjdF0iPT09T2JqZWN0LnByb3RvdHlwZS50b1N0cmluZy5jYWxsKHQpPyJvYmplY3Qgd2l0aCBrZXlzIHsiK09iamVjdC5rZXlzKHQpLmpvaW4oIiwgIikrIn0iOnQsIiIpKX1mdW5jdGkKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpFcnJvcjogTWluaWZpZWQgUmVhY3QgZXJyb3IgIzMxOyB2aXNpdCBodHRwczovL3JlYWN0anMub3JnL2RvY3MvZXJyb3ItZGVjb2Rlci5odG1sP2ludmFyaWFudD0zMSZhcmdzW109b2JqZWN0JTIwd2l0aCUyMGtleXMlMjAlN0Jjb2RlJTJDJTIwbWVzc2FnZSUyQyUyMGElN0QmYXJnc1tdPSBmb3IgdGhlIGZ1bGwgbWVzc2FnZSBvciB1c2UgdGhlIG5vbi1taW5pZmllZCBkZXYgZW52aXJvbm1lbnQgZm9yIGZ1bGwgZXJyb3JzIGFuZCBhZGRpdGlvbmFsIGhlbHBmdWwgd2FybmluZ3MuCkVycm9yOiBNaW5pZmllZCBSZWFjdCBlcnJvciAjMzE7IHZpc2l0IGh0dHBzOi8vcmVhY3Rqcy5vcmcvZG9jcy9lcnJvci1kZWNvZGVyLmh0bWw/aW52YXJpYW50PTMxJmFyZ3NbXT1vYmplY3QlMjB3aXRoJTIwa2V5cyUyMCU3QmNvZGUlMkMlMjBtZXNzYWdlJTJDJTIwYSU3RCZhcmdzW109IGZvciB0aGUgZnVsbCBtZXNzYWdlIG9yIHVzZSB0aGUgbm9uLW1pbmlmaWVkIGRldiBlbnZpcm9ubWVudCBmb3IgZnVsbCBlcnJvcnMgYW5kIGFkZGl0aW9uYWwgaGVscGZ1bCB3YXJuaW5ncy4KICAgIGF0IFNvIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMDNhYWE0NjguY2h1bmsuanM6MToxOTExMzgpCiAgICBhdCBkIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMDNhYWE0NjguY2h1bmsuanM6MToxOTI3NzgpCiAgICBhdCB2IChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMDNhYWE0NjguY2h1bmsuanM6MToxOTM4OTEpCiAgICBhdCBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMDNhYWE0NjguY2h1bmsuanM6MToxOTU5NzQKICAgIGF0IExhIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMDNhYWE0NjguY2h1bmsuanM6MToyMDU0ODApCiAgICBhdCBidSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjAzYWFhNDY4LmNodW5rLmpzOjE6MjQ2MTMxKQogICAgYXQgYmwgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi4wM2FhYTQ2OC5jaHVuay5qczoxOjIzNjc0OCkKICAgIGF0IHlsIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMDNhYWE0NjguY2h1bmsuanM6MToyMzY2NzMpCiAgICBhdCBzbCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjAzYWFhNDY4LmNodW5rLmpzOjE6MjMzNjc1KQogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjAzYWFhNDY4LmNodW5rLmpzOjE6MTg0ODY1
```

**Comment by Pokegali** [comment]
This is base64, it can be decoded into
```
>ring"!==typeof e)throw Error(a(284));if(!n._owner)throw Error(a(290,e))}return e}function So(e,t){if("textarea"!==e.type)throw Error(a(31,"[object Object]"===Object.prototype.toString.call(t)?"object with keys {"+Object.keys(t).join(", ")+"}":t,""))}functi
                                                                                                                               ^


Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bcode%2C%20message%2C%20a%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warn
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bcode%2C%20message%2C%20a%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warn
    at So (https://cybercodeonline.com/static/js/main.03aaa468.chunk.js:1:191138)
    at d (https://cybercodeonline.com/static/js/main.03aaa468.chunk.js:1:192778)
    at v (https://cybercodeonline.com/static/js/main.03aaa468.chunk.js:1:193891)
    at https://cybercodeonline.com/static/js/main.03aaa468.chunk.js:1:195974
    at La (https://cybercodeonline.com/static/js/main.03aaa468.chunk.js:1:205480)
    at bu (https://cybercodeonline.com/static/js/main.03aaa468.chunk.js:1:246131)
    at bl (https://cybercodeonline.com/static/js/main.03aaa468.chunk.js:1:236748)
    at yl (https://cybercodeonline.com/static/js/main.03aaa468.chunk.js:1:236673)
    at sl (https://cybercodeonline.com/static/js/main.03aaa468.chunk.js:1:233675)
    at https://cybercodeonline.com/static/js/main.03aaa468.chunk.js:1:184865
```

But I have absolutely no idea why there is this error, just wanted to translate the error message
