### ISSUE TITLE
Game crashing with error

### ISSUE THREAD

**Issue by twystd** [DexterHuang/CyberCodeOnline#285]
Error occurred while trying to pick up loot in a dungeon and can no longer open the game - it reports the following (decoded) error on opening:

>le:{display:"block",whiteSpace:"nowrap",paddingBottom:128}},t)))},zt=function(e){var t=e.children,n=20-Math.ceil(t.length/2),a=new Array(n).fill("-").join("");return r.createElement(r.Fragment,null,r.createElement(je,null),r.createElement(je,null,r.createE
                                                                                                                               ^
RangeError: Invalid array length
RangeError: Invalid array length
    at zt (https://cybercodeonline.com/static/js/AppLayoutDesktop.5a588fbc.chunk.js:1:45185)
    at $o (https://cybercodeonline.com/static/js/main.78c12761.chunk.js:1:753754)
    at gu (https://cybercodeonline.com/static/js/main.78c12761.chunk.js:1:800271)
    at gc (https://cybercodeonline.com/static/js/main.78c12761.chunk.js:1:792908)
    at mc (https://cybercodeonline.com/static/js/main.78c12761.chunk.js:1:792833)
    at sc (https://cybercodeonline.com/static/js/main.78c12761.chunk.js:1:789835)
    at https://cybercodeonline.com/static/js/main.78c12761.chunk.js:1:741025
    at t.unstable_runWithPriority (https://cybercodeonline.com/static/js/main.78c12761.chunk.js:1:816695)
    at Wi (https://cybercodeonline.com/static/js/main.78c12761.chunk.js:1:740735)
    at Yi (https://cybercodeonline.com/static/js/main.78c12761.chunk.js:1:740971)

**Comment by twystd** [comment]
Seems to be fixed with the latest update
